# This dependabot configuration keeps the actions versions in the template workflows up to date,
# to prevent version rollbacks when those template workflows are synced to other repos.
# 
# There is also a separate template dependabot.yml config that is synced to other Neurobagel repos:
# https://github.com/neurobagel/workflows/tree/main/template_workflows/dependabot.yml

version: 2
updates:

  # See also https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
  - package-ecosystem: "github-actions"
    directories: 
      - "/template_workflows/*"
    schedule:
      interval: "weekly"
    labels:
      - "_bot"
      - "dependencies"
