# This dependabot configuration is for keeping the actions up to date for the template workflows,
# to prevent version rollbacks when those template workflows are synced to other repos.
# 
# For the actual template dependabot.yml that is synced to other Neurobagel repos,
# see https://github.com/neurobagel/workflows/tree/main/template_workflows/dependabot.yml

version: 2
updates:

  # See also https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
  - package-ecosystem: "github-actions"
    directories: 
      - "/template_workflows/*"
    schedule:
      interval: "weekly"
    labels:
      - "_bot"
      - "dependencies"
