group:
  # Workflows related to project automation
  - files: 
      - source: template_workflows/project_automation/
        dest: .github/workflows/
    repos: |
      neurobagel/annotation_tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/bagelschema
      neurobagel/bulk_annotations
      neurobagel/browbids
      neurobagel/digest
      neurobagel/documentation
      neurobagel/neurobagel_examples
      neurobagel/federation-api
      neurobagel/menu
      neurobagel/openneuro-annotations
      neurobagel/planning
      neurobagel/project
      neurobagel/query-tool
      neurobagel/recipes
      neurobagel/workflows
  
  # Workflow and configuration files for auto-releasing with intuit/auto
  - files:
      - source: template_workflows/auto_release/release.yaml
        dest: .github/workflows/release.yaml
      - source: template_configs/.autorc
        dest: .autorc
      - source: template_prs/auto_release_repo_pr.md
        dest: .github/pull_request_template.md
    # TODO: add JS repos once React migration is complete?
    repos: |
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/federation-api

# Workflows to build + push SEMVER Docker image on release
neurobagel/api:
  - source: template_workflows/auto_release/build_docker_on_release.yml
    dest: .github/workflows/build_docker_on_release.yml
    template:
      synced_repo:
        docker_repo_name: 'api'

neurobagel/bagel-cli:
  - source: template_workflows/auto_release/build_docker_on_release.yml
    dest: .github/workflows/build_docker_on_release.yml
    template:
      synced_repo:
        docker_repo_name: 'bagelcli'

neurobagel/federation-api:
  - source: template_workflows/auto_release/build_docker_on_release.yml
    dest: .github/workflows/build_docker_on_release.yml
    template:
      synced_repo:
        docker_repo_name: 'federation_api'