group:
  # Workflows related to project automation
  - files: 
      - source: template_workflows/project_automation/
        dest: .github/workflows/
    repos: |
      neurobagel/annotation_tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/bagelschema
      neurobagel/bulk_annotations
      neurobagel/browbids
      neurobagel/digest
      neurobagel/documentation
      neurobagel/neurobagel_examples
      neurobagel/federation-api
      neurobagel/menu
      neurobagel/openneuro-annotations
      neurobagel/planning
      neurobagel/project
      neurobagel/query-tool
      neurobagel/recipes
      neurobagel/tools
      neurobagel/workflows
      neurobagel/ui
  
  # Workflow and configuration files for auto-releasing with intuit/auto
  - files:
      - source: template_workflows/auto_release/release.yaml
        dest: .github/workflows/release.yaml
      - source: template_configs/.autorc
        dest: .autorc
    repos: |
      neurobagel/query-tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/federation-api
      neurobagel/tools
      neurobagel/recipes
      neurobagel/ui

  # Workflow to build + push SEMVER Docker image on release
  # NOTE: Each repo needs to have a secret with the name DOCKERHUB_REPO set up 
  # which refers to the DockerHub repository name
  - files: 
      - source: template_workflows/auto_release/build_docker_on_release.yml
        dest: .github/workflows/build_docker_on_release.yml
    repos: |
      neurobagel/query-tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/federation-api
      neurobagel/tools
      neurobagel/ui

  # Workflow to build + push Docker nightly image
  # NOTE: Each repo needs to have a secret with the name DOCKERHUB_REPO set up 
  # which refers to the DockerHub repository name
  - files: 
      - source: template_workflows/build_docker_nightly.yml
        dest: .github/workflows/build_docker_nightly.yml
    repos: |
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/federation-api
      neurobagel/tools
      neurobagel/ui

  - files:
      - source: template_configs/LICENSE
        dest: LICENSE
    repos: |
      neurobagel/annotation_tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/bagelschema
      neurobagel/digest
      neurobagel/documentation
      neurobagel/neurobagel_examples
      neurobagel/federation-api
      neurobagel/menu
      neurobagel/openneuro-annotations
      neurobagel/planning
      neurobagel/project
      neurobagel/query-tool
      neurobagel/recipes
      neurobagel/tools
      neurobagel/workflows
      neurobagel/ui
