group:
  # Workflows related to project automation
  - files: 
      - source: template_workflows/project_automation/
        dest: .github/workflows/
    repos: |
      neurobagel/annotation-tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/bagelschema
      neurobagel/bulk_annotations
      neurobagel/browbids
      neurobagel/digest
      neurobagel/documentation
      neurobagel/neurobagel_examples
      neurobagel/federation-api
      neurobagel/menu
      neurobagel/openneuro-annotations
      neurobagel/planning
      neurobagel/project
      neurobagel/query-tool
      neurobagel/recipes
      neurobagel/tools
      neurobagel/workflows
      neurobagel/ui
      neurobagel/communities
      neurobagel/bump-dictionary
      neurobagel/dev-docs
  
  # Dependabot configuration file synchronization
  - files:
      - source: template_workflows/dependabot.yml
        dest: .github/dependabot.yml
    repos: |
      neurobagel/annotation-tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/bagelschema
      neurobagel/digest
      neurobagel/documentation
      neurobagel/neurobagel_examples
      neurobagel/federation-api
      neurobagel/menu
      neurobagel/openneuro-annotations
      neurobagel/planning
      neurobagel/query-tool
      neurobagel/recipes
      neurobagel/tools
      neurobagel/ui
      neurobagel/react-bagel
      neurobagel/communities
      neurobagel/bump-dictionary

  # auto release for python projects on PyPI
  - files:
      - source: template_workflows/auto_release/release_pypi.yaml
        dest: .github/workflows/release.yaml
      - source: template_configs/.autorc_pypi
        dest: .autorc
    repos: |
      neurobagel/bagel-cli
      neurobagel/bump-dictionary

  # auto release for "default" projects (e.g. Python without PyPI)
  - files:
      - source: template_workflows/auto_release/release_default.yaml
        dest: .github/workflows/release.yaml
      - source: template_configs/.autorc_default
        dest: .autorc
    repos: |
      neurobagel/api
      neurobagel/federation-api
      neurobagel/tools
      neurobagel/recipes

  # auto release for javascript projects
  - files:
      - source: template_workflows/auto_release/release_default.yaml
        dest: .github/workflows/release.yaml
      - source: template_configs/.autorc_js
        dest: .autorc
    repos: |
      neurobagel/query-tool
      neurobagel/annotation-tool
      neurobagel/ui

  # Workflow to build + push SEMVER Docker image on release
  # NOTE: Each repo needs to have a secret with the name DOCKERHUB_REPO set up 
  # which refers to the DockerHub repository name
  - files: 
      - source: template_workflows/auto_release/build_docker_on_release.yml
        dest: .github/workflows/build_docker_on_release.yml
    repos: |
      neurobagel/annotation-tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/federation-api
      neurobagel/tools
      neurobagel/ui

  # Workflow to build + push Docker nightly image
  # NOTE: Each repo needs to have a secret with the name DOCKERHUB_REPO set up 
  # which refers to the DockerHub repository name
  - files: 
      - source: template_workflows/build_docker_nightly.yml
        dest: .github/workflows/build_docker_nightly.yml
    repos: |
      neurobagel/api
      neurobagel/federation-api
      neurobagel/tools
      neurobagel/ui

  - files:
      - source: template_configs/LICENSE
        dest: LICENSE
    repos: |
      neurobagel/annotation-tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/bagelschema
      neurobagel/digest
      neurobagel/documentation
      neurobagel/neurobagel_examples
      neurobagel/federation-api
      neurobagel/menu
      neurobagel/openneuro-annotations
      neurobagel/planning
      neurobagel/project
      neurobagel/query-tool
      neurobagel/recipes
      neurobagel/tools
      neurobagel/workflows
      neurobagel/ui
      neurobagel/communities
      neurobagel/bump-dictionary
