group:
  # Workflows related to project automation
  - files: 
      - source: template_workflows/project_automation/
        dest: .github/workflows/
    repos: |
      neurobagel/annotation_tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/bagelschema
      neurobagel/bulk_annotations
      neurobagel/browbids
      neurobagel/digest
      neurobagel/documentation
      neurobagel/neurobagel_examples
      neurobagel/federation-api
      neurobagel/menu
      neurobagel/openneuro-annotations
      neurobagel/planning
      neurobagel/project
      neurobagel/query-tool
      neurobagel/recipes
      neurobagel/tools
      neurobagel/workflows
  
  # Workflow and configuration files for auto-releasing with intuit/auto
  - files:
      - source: template_workflows/auto_release/release.yaml
        dest: .github/workflows/release.yaml
      - source: template_configs/.autorc
        dest: .autorc
      - source: template_prs/auto_release_repo_pr.md
        dest: .github/pull_request_template.md
    # TODO: add JS repos once React migration is complete?
    repos: |
      neurobagel/query-tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/federation-api

  - files:
      - source: template_configs/LICENSE
        dest: LICENSE
    # TODO: add JS repos once React migration is complete?
    repos: |
      neurobagel/annotation_tool
      neurobagel/api
      neurobagel/bagel-cli
      neurobagel/bagelschema
      neurobagel/digest
      neurobagel/documentation
      neurobagel/neurobagel_examples
      neurobagel/federation-api
      neurobagel/menu
      neurobagel/openneuro-annotations
      neurobagel/planning
      neurobagel/project
      neurobagel/query-tool
      neurobagel/react-bagel
      neurobagel/recipes
      neurobagel/tools
      neurobagel/workflows

  # # Workflows for python repositories
  # - files:
  #     - source: template_configs/README.md
  #       dest: README.md
  #   repos: |
  #     neurobagel/api
  #     neurobagel/bagel-cli
  #     neurobagel/digest
  #     neurobagel/federation-api
  #     neurobagel/tools

  # # Workflows for React repositories
  # - files:
  #     - source: template_configs/README.md
  #       dest: README.md
  #   repos: |
  #     neurobagel/query-tool
  #     neurobagel/react-bagel

# TODO: look into using a single workflow for all repos
# See also: https://github.com/neurobagel/workflows/issues/92
# Workflows to build + push SEMVER Docker image on release
neurobagel/query-tool:
  - source: template_workflows/auto_release/build_docker_on_release.yml
    dest: .github/workflows/build_docker_on_release.yml
    template:
      synced_repo:
        dockerhub_username: '${{ secrets.DOCKERHUB_USERNAME }}'
        dockerhub_token: '${{ secrets.DOCKERHUB_TOKEN }}'
        docker_repo_name: 'query_tool'
        release_tag: '${{ github.event.release.tag_name }}'

neurobagel/api:
  - source: template_workflows/auto_release/build_docker_on_release.yml
    dest: .github/workflows/build_docker_on_release.yml
    template:
      synced_repo:
        dockerhub_username: '${{ secrets.DOCKERHUB_USERNAME }}'
        dockerhub_token: '${{ secrets.DOCKERHUB_TOKEN }}'
        docker_repo_name: 'api'
        release_tag: '${{ github.event.release.tag_name }}'

neurobagel/bagel-cli:
  - source: template_workflows/auto_release/build_docker_on_release.yml
    dest: .github/workflows/build_docker_on_release.yml
    template:
      synced_repo:
        dockerhub_username: '${{ secrets.DOCKERHUB_USERNAME }}'
        dockerhub_token: '${{ secrets.DOCKERHUB_TOKEN }}'
        docker_repo_name: 'bagelcli'
        release_tag: '${{ github.event.release.tag_name }}'

neurobagel/federation-api:
  - source: template_workflows/auto_release/build_docker_on_release.yml
    dest: .github/workflows/build_docker_on_release.yml
    template:
      synced_repo:
        dockerhub_username: '${{ secrets.DOCKERHUB_USERNAME }}'
        dockerhub_token: '${{ secrets.DOCKERHUB_TOKEN }}'
        docker_repo_name: 'federation_api'
        release_tag: '${{ github.event.release.tag_name }}'
