# This is a centrally maintained dependabot configuration file
# that is applied to all repositories in the neurobagel organization.
# Do not make changes to this file directly. Instead, make changes
# to the template file in the workflows: https://github.com/neurobagel/workflows/tree/main/template_workflows/project_automation

version: 2
updates:

  # We instruct dependabot to open PRs if a newer version
  # of a github action has been released.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "_bot"
      - "dependencies"
  
  # We instruct dependabot to open PRs whenever the HEAD of 
  # of a submodule repository has advanced beyond what our submodule
  # is currently tracking.
  # Note: this workflow is only relevant for repositories that have
  # submodules.
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - '_bot'
      - 'dependencies'

  # We instruct dependabot to open PRs both for security vulnerabilities
  # and for patch and minor version updates of javascript / npm dependencies.
  # Note: this workflow is only relevant for repositories that have
  # a package.json file / use npm.
  - package-ecosystem: 'npm'
    schedule:
      interval: 'weekly'
    # This setting asks dependabot to group PRs for version updates of all development or production dependencies
    # into single PRs to reduce the total number of PRs opened.
    groups:
      production-dependencies:
        applies-to: version-updates
        dependency-type: 'production'
      development-dependencies:
        applies-to: version-updates
        dependency-type: 'development'
    # We ignore all major version updates of dependencies.
    # The idea is that we only bump major versions manually or if doing
    # so addresses a security vulnerability.
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - '_bot'
      - 'dependencies'

  # We instruct dependabot to open PRs both for security vulnerabilities
  # of python / pip dependencies.
  # Note: this workflow is only relevant for repositories that have
  # a requirements.txt file / use python / pip.
  - package-ecosystem: 'pip'
    schedule:
      interval: 'daily'
    # This setting instructs dependabot to not open PRs for version updates
    # but to still open PRs for security vulnerabilities.
    open-pull-requests-limit: 0
    labels:
      - '_bot'
      - 'dependencies'