name: build Docker image on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: {{ synced_repo.dockerhub_username }}
          password: {{ synced_repo.dockerhub_token }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: {{ synced_repo.dockerhub_username }}/{{ synced_repo.docker_repo_name }}:latest, {{ synced_repo.dockerhub_username }}/{{ synced_repo.docker_repo_name }}:{{ synced_repo.release_tag }}
